# .bashrc

# Source global definitions

[ -z "$PS1" ] && return

if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f $HOME/bash_aliases ]; then
	. $HOME/bash_aliases
fi

## Shell varibles
export OOO_FORCE_DESKTOP=gnome
export BROWSER='firefox'
export PAGER=less
export EDITOR=emacs
export PATH=$PATH:$HOME/bin:/usr/local/bin
export LESS='-R'
export HISTCONTROL=ignoredups
export HISTSIZE=5000
export HISTFILESIZE=1000
export HISTIGNORE="&:ls:ll:la:l.:pwd:exit:clear"

PS1="[\u - - \w]\$\n"
export PS1
